CREATE TABLE INGREDIENT
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME             VARCHAR(255) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    PRICE            BIGINT,
    TYPE             VARCHAR(255),
    PICTURE          BLOB,
    CREATED_BY       VARCHAR(255),
    DATE_OF_CREATION DATETIME,
    CHANGED_BY       VARCHAR(255),
    DATE_OF_CHANGE   DATETIME,
    ACTIVITY         BOOLEAN
);
INSERT INTO INGREDIENT (NAME, DESCRIPTION, PRICE, TYPE, CREATED_BY, DATE_OF_CREATION, CHANGED_BY, DATE_OF_CHANGE, ACTIVITY)
VALUES ('Milk', 'Basic ingredient', '1', 'Dairy', 'Viktoria Delija', '2023-09-09', 'Viktoria Delija', '2023-09-09', 1),
       ('Bread', 'Basic ingredient', '1', 'Bread', 'Viktoria Delija', '2023-09-09', 'Viktoria Delija', '2023-09-09', 1);
CREATE TABLE AUTHOR
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME        VARCHAR(255) NOT NULL,
    LASTNAME         VARCHAR(255) NOT NULL,
    EMAIL            VARCHAR(255) NOT NULL,
    PASSWORD         VARCHAR(255) NOT NULL,
    ROLE             VARCHAR(255) NOT NULL,
    CREATED_BY       VARCHAR(255),
    DATE_OF_CREATION DATETIME,
    CHANGED_BY       VARCHAR(255),
    DATE_OF_CHANGE   DATETIME,
    ACTIVITY         BOOLEAN
);
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLE, CREATED_BY, DATE_OF_CREATION, CHANGED_BY,
                    DATE_OF_CHANGE, ACTIVITY)
VALUES ('Viktoria', 'Delija', 'viktoria.delija@example.com', '123', 'Admin', 'Viktoria Delija', '2023-09-09',
        'Viktoria Delija', '2023-09-09', 1);
CREATE TABLE RECIPE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME             VARCHAR(255) NOT NULL,
    DESCRIPTION      VARCHAR(255) NOT NULL,
    INGREDIENTS      VARCHAR(255) NOT NULL,
    INSTRUCTIONS     VARCHAR(255) NOT NULL,
    AUTHOR_ID        BIGINT       NOT NULL,
    PICTURE          BLOB,
    CREATED_BY       VARCHAR(255),
    DATE_OF_CREATION DATETIME,
    CHANGED_BY       VARCHAR(255),
    DATE_OF_CHANGE   DATETIME,
    ACTIVITY         BOOLEAN,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR
);
CREATE TABLE MY_RECIPES
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID        BIGINT NOT NULL,
    RECIPE_ID        BIGINT NOT NULL,
    CREATED_BY       VARCHAR(255),
    DATE_OF_CREATION DATETIME,
    CHANGED_BY       VARCHAR(255),
    DATE_OF_CHANGE   DATETIME,
    ACTIVITY         BOOLEAN,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE
);
CREATE TABLE LIST_INGREDIENTS
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    RECIPE_ID        BIGINT NOT NULL,
    INGREDIENT_ID    BIGINT NOT NULL,
    CREATED_BY       VARCHAR(255),
    DATE_OF_CREATION DATETIME,
    CHANGED_BY       VARCHAR(255),
    DATE_OF_CHANGE   DATETIME,
    ACTIVITY         BOOLEAN,
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE
);
